google.maps.__gjsload__('geometry', function(_){var ssa=function(a,b){return Math.abs(_.tl(b-a,-180,180))},tsa=function(a,b,c,d,e){if(!d){c=ssa(a.lng(),c)/ssa(a.lng(),b.lng());if(!e)return e=Math.sin(_.Gk(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Gk(b.lat())),_.Hk(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.Bn(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Gk(a.lat());a=_.Gk(a.lng());d=_.Gk(b.lat());b=_.Gk(b.lng());c=_.Gk(c);return _.tl(_.Hk(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},usa=function(a,b){a=new _.jm(a,!1);b=new _.jm(b,!1);return a.equals(b)},vsa=function(a,b,c){a=_.sm(a);c=c||1E-9;var d=_.tl(a.lng(),-180,180),e=b instanceof _.Rs,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(let q=0,t=g.getLength();q<t;++q){let x=g.getAt(q),A=x.getLength(),C=e?A:A-1;for(let L=0;L<C;++L){var h=x.getAt(L);let N=x.getAt((L+1)%A);
if(usa(h,a)||usa(N,a))return!0;var k=_.tl(h.lng(),-180,180),l=_.tl(N.lng(),-180,180);let T=Math.max(k,l),B=Math.min(k,l);if(k=Math.abs(_.tl(k-l,-180,180))<=1E-9&&(Math.abs(_.tl(k-d,-180,180))<=c||Math.abs(_.tl(l-d,-180,180))<=c)){k=a.lat();l=Math.min(h.lat(),N.lat())-c;var n=Math.max(h.lat(),N.lat())+c;k=k>=l&&k<=n}if(k)return!0;if(T-B>180?d+c>=T||d-c<=B:d+c>=B&&d-c<=T)if(h=tsa(h,N,d,f,b),Math.abs(h-a.lat())<c)return!0}}return!1},wsa=function(a,b){var c=_.km(a);a=_.lm(a);var d=_.km(b);b=_.lm(b);return 2*
Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))},xsa=function(a,b,c){a=_.sm(a);b=_.sm(b);c=c||6378137;return wsa(a,b)*c},Asa=function(a,b){b=b||6378137;a instanceof _.co&&(a=a.getArray());a=(0,_.Cr)(a);if(a.length===0)return 0;var c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);ysa(a[a.length-1],f);for(let x=0;x<a.length;++x)ysa(a[x],d),sB(f,d,c),zsa(c,e,e),[f[0],f[1],f[2]]=d;var [g,h,k]=f,[l,n,q,t]=e;return 2*Math.atan2(g*n+h*q+k*t,l)*(b*b)},
Bsa=function(a,b){if(isFinite(a)){var c=a%360;a=Math.round(c/90);c-=a*90;if(c===30||c===-30){c=Math.sign(c)*.5;var d=Math.sqrt(.75)}else c===45||c===-45?(c=Math.sign(c)*Math.SQRT1_2,d=Math.SQRT1_2):(d=c/180*Math.PI,c=Math.sin(d),d=Math.cos(d));switch(a&3){case 0:b[0]=c;b[1]=d;break;case 1:b[0]=d;b[1]=-c;break;case 2:b[0]=-c;b[1]=-d;break;default:b[0]=-d,b[1]=c}}else b[0]=NaN,b[1]=NaN},ysa=function(a,b){var c=Array(2);Bsa(a.lat(),c);var [d,e]=c;Bsa(a.lng(),c);var [f,g]=c;b[0]=e*g;b[1]=e*f;b[2]=d},
zsa=function(a,b,c){var d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f},sB=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2],g=a[0]+b[0],h=a[1]+b[1],k=a[2]+b[2],l=g*g+h*h+k*k,n=e*k-f*h;f=f*g-d*k;d=d*h-e*g;e=l*l+n*n+f*f+d*d;if(e!==0)b=Math.sqrt(e),c[0]=l/b,c[1]=n/b,c[2]=f/b,c[3]=d/b;else{a:for(l=[a[0]-b[0],a[1]-b[1],a[2]-b[2]],n=0;n<3;++n)if(l[n]!==
0){if(l[n]<0){l=[-l[0],-l[1],-l[2]];break a}break}n=0;for(f=1;f<l.length;++f)Math.abs(l[f])<Math.abs(l[n])&&(n=f);f=[0,0,0];f[n]=1;l=[l[1]*f[2]-l[2]*f[1],l[2]*f[0]-l[0]*f[2],l[0]*f[1]-l[1]*f[0]];n=Math.hypot(...l);l=[l[0]/n,l[1]/n,l[2]/n];n=Array(4);sB(a,l,n);a=Array(4);sB(l,b,a);zsa(a,n,c)}},tB=class{};tB.isLocationOnEdge=vsa;
tB.containsLocation=function(a,b){a=_.sm(a);var c=_.tl(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;var g=!1;for(let k=0,l=e.getLength();k<l;++k){let n=e.getAt(k);for(let q=0,t=n.getLength();q<t;++q){let x=n.getAt(q),A=n.getAt((q+1)%t);var h=_.tl(x.lng(),-180,180);let C=_.tl(A.lng(),-180,180),L=Math.max(h,C);h=Math.min(h,C);(L-h>180?c>=L||c<h:c<L&&c>=h)&&tsa(x,A,c,d,f)<a.lat()&&(g=!g)}}return g||vsa(a,b)};var uB=class{};uB.computeSignedArea=Asa;
uB.computeArea=function(a,b){if(!(a instanceof _.co||Array.isArray(a)||a instanceof _.kn||a instanceof _.ko))try{a=_.mn(a)}catch(c){try{a=new _.ko((0,_.Uja)(a))}catch(d){throw _.Ql("Invalid path passed to computeArea(): "+JSON.stringify(a));}}b=b||6378137;if(a instanceof _.ko){if(a.getRadius()===void 0)throw _.Ql("Invalid path passed to computeArea(): Circle is missing radius.");if(a.getRadius()<0)throw _.Ql("Invalid path passed to computeArea(): Circle must have non-negative radius.");if(b<0)throw _.Ql("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");
if(a.getRadius()>Math.PI*b)throw _.Ql("Invalid path passed to computeArea(): Circle must not cover more than 100% of the sphere.");return 2*Math.PI*b**2*(1-Math.cos(a.getRadius()/b))}if(a instanceof _.kn){if(b<0)throw _.Ql("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");if(a.lat.lo>a.lat.hi)throw _.Ql("Invalid path passed to computeArea(): the southern LatLng of a LatLngBounds cannot be more north than the northern LatLng.");let c=2*Math.PI*b**2*(1-Math.cos((a.lat.lo-
90)*Math.PI/180));c-=2*Math.PI*b**2*(1-Math.cos((a.lat.hi-90)*Math.PI/180));return c*Math.abs(a.lng.hi-a.lng.lo)/360}return Math.abs(Asa(a,b))};uB.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.co&&(a=a.getArray());for(let d=0,e=a.length-1;d<e;++d)c+=xsa(a[d],a[d+1],b);return c};uB.computeDistanceBetween=xsa;uB.traversePath=function(){throw Error("traversePath() is not available in this version of the Maps JavaScript API.");};
uB.interpolate=function(a,b,c){a=_.sm(a);b=_.sm(b);var d=_.km(a),e=_.lm(a),f=_.km(b),g=_.lm(b),h=Math.cos(d),k=Math.cos(f);b=wsa(a,b);var l=Math.sin(b);if(l<1E-6)return new _.jm(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.jm(_.Hk(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Hk(Math.atan2(e,b)))};
uB.computeOffsetOrigin=function(a,b,c,d){a=_.sm(a);c=_.Gk(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.km(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(f<0)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.lm(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.jm(_.Hk(g),_.Hk(a))};
uB.computeOffset=function(a,b,c,d){a=_.sm(a);b/=d||6378137;c=_.Gk(c);var e=_.km(a);a=_.lm(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.jm(_.Hk(Math.asin(g)),_.Hk(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};uB.computeHeading=function(a,b){a=_.sm(a);b=_.sm(b);var c=_.km(a),d=_.lm(a);a=_.km(b);b=_.lm(b)-d;return _.tl(_.Hk(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)};var Csa={encoding:_.nt,spherical:uB,poly:tB};_.Xa.google.maps.geometry=Csa;_.Yk("geometry",Csa);});
